= Hifimagnet basic workflow TOSCA

== Running in the orchestrator CLI

* Create a `local-blueprint-inputs.yaml` from the template file.
** Define the HPC ressource you are planning to use.
** Enter your credentials (`user/passwd`)
** Setup <<input parameters, inputs>>

First clone the `resources`:
[source]
----
mkdir -p MSO4SC && cd $_
git clone https://github.com/MSO4SC/resources.git
git pull MSO4SC/resources
----

* Connect to the cloudify client via docker:
[source]
----
docker pull mso4sc/msoorchestrator-cli
docker run -it --rm \
    -v $HOME/MSO4SC/resources:/resources \
     mso4sc/msoorchestrator-cli
----

* Within the docker:
[source]
----
cfy profiles use  ORCHESTRATOR_IP -t  default_tenant -u USER -p PASSWD
----

Then you can simply deploy your application using:
[source]
----
./deploy up
----

To undeploy on the orchestrator, just:
[source]
----
./deploy down
----

NOTE: If the application fails during one step of the deploy up process, you'll have to
force cancel execution by hands. `cfy executions list`, `cfy executions cancel -f <id>`
in the orchestrator client (*docker).

See https://github.com/MSO4SC/MSOOrchestrator-CLI/blob/master/README.adoc#remote-mode for details


== Package workflow for {MSO4SC} portal

To package the workflow for latter use in the portal, just create a gzipped archive `hifimagnet_test.tgz`
using :
[source]
----
./deploy pkg
----

[#inputs]
== Input parameters

=== HPC settings

=== Simulation setup

=== Singularity images

== Synopsis

* deploy:
** load singularity {hifimagnet} image
** eventually load dataset from CKAN URL
** perform a few checks [TODO]

* running:
** move to base_dir/workdir_tmp_ID
** submit batch prefix_ID using workload manager

* undeploy:
** eventually cleanup base_dir/workir_prefix_ID
** eventually cleanup singularity image
** remove loaded dataset



==
