#############################
# Configure the application
# Generated via MSO4SC Portal.
#############################

feelpp_mesh_create:
    enable: True
    geofile: "/usr/local/share/feelpp/testcases/CSM/torsionbar/torsionbar.geo"
    mshfile: "/feel/torsionbar.msh"
    dim: 3
    opts: ""
    job_tasks: 1
    job_tasks_per_nodes: 1
    job_nodes: 1
    job_max_time: "00:10:00"
    job_hpc_partition: 'thin-shared'
    job_hpc_modules: ['gcc/6.1.0','openmpi/1.10.2','singularity/2.4.2']
    job_hpc_workdir: '${LUSTRE}/mso4sc_orchestrator'
    job_hpc_volumes: ['/scratch','/mnt','${LUSTRE}/mso4sc_orchestrator/feel:/feel']
    girder_repo_url: "https://girder.math.unistra.fr"
    girder_api_key: ""
    girder_folder_id: "5a627108b0e9570150cb23f5"
    singularity_image_file: "feelpp_feelpp-toolboxes-mso4sc.simg"
    revert_no_erase: 'True'
    avoid_cleanup: True

feelpp_mesh_part:
    enable: True
    mshfile: "/feel/torsionbar.msh"
    part: 4
    mesh_parted_name: "torsionbar_parted"
    opts: ""
    job_tasks: 1
    job_tasks_per_nodes: 1
    job_nodes: 1
    job_max_time: "00:10:00"
    job_hpc_partition: 'thin-shared'
    job_hpc_workdir: '${LUSTRE}/mso4sc_orchestrator'
    job_hpc_modules: ['gcc/6.1.0','openmpi/1.10.2','singularity/2.4.2']
    job_hpc_workdir: '${LUSTRE}/mso4sc_orchestrator'
    job_hpc_volumes: ['/scratch','/mnt','${LUSTRE}/mso4sc_orchestrator/feel:/feel']
    girder_repo_url: "https://girder.math.unistra.fr"
    girder_api_key: ""
    girder_folder_id: "5a627108b0e9570150cb23f5"
    singularity_image_file: "feelpp_feelpp-toolboxes-mso4sc.simg"
    revert_no_erase: 'True'
    avoid_cleanup: True

feelpp_toolboxes:
    enable: True
    toolbox: "solid"
    dim: 3
    cfg: "/usr/local/share/feelpp/testcases/CSM/torsionbar/torsionbar.cfg"
    mesh_parted_name: "torsionbar_parted"
    opts: "--pc-view 1"
    job_tasks: 4
    job_tasks_per_nodes: 4
    job_nodes: 1
    job_max_time: "00:30:00"
    job_hpc_partition: 'thin-shared'
    job_hpc_workdir: '${LUSTRE}/mso4sc_orchestrator'
    job_hpc_modules: ['gcc/6.1.0','openmpi/1.10.2','singularity/2.4.2']
    job_hpc_workdir: '${LUSTRE}/mso4sc_orchestrator'
    job_hpc_volumes: ['/scratch','/mnt','${LUSTRE}/mso4sc_orchestrator/feel:/feel']
    girder_repo_url: "https://girder.math.unistra.fr"
    girder_api_key: ""
    girder_folder_id: "5a627108b0e9570150cb23f5"
    singularity_image_file: "feelpp_feelpp-toolboxes-mso4sc.simg"
    revert_no_erase: 'True'
    avoid_cleanup: True
