= Blueprint Examples

MSO4SC TOSCA blueprint examples.

== General use

The examples uses by default the Finis Terrae II HPC, but no credentials are provided. To use your own credentials, copy the file `local-blueprint-inputs-example.yaml` to `local-blueprint-inputs.yaml` and complete the file with your user name and password. To use other HPCs, add them to the `local-blueprint-inputs.yaml` and modify the examples as needed.

Every example has two scripts in the root folder:

* *[example]-up.sh* upload the blueprint, creates the deployment, run the _install_ workflow and finally run the application with the _run_jobs_ workflow.
* *[example]-down.sh*

Besides there are two scripts to help stop or cancel an execution.

* *force-cancel.sh* If for some reason the execution is hanged, cancel with this command. It receives the execution id as parameter. Use `cfy executions list` to see all executions status and ids.
* *stop-instance.sh* Stops a node-instance, if necessary. It receives the node instance id as parameter. Use `cfy node-instances list` to see all node instances status and ids.

== Examples description

* *single-srun-job* Single job execution using srun command. Uses two dummy deployment scripts that create a file using `touch` command.
* *single-sbatch-job* Single job execution using sbatch command. Uses two deployment scripts that create the sbatch script file in the HPC and removes it.
* *single-singularity-job* Single job execution using a singularity container. Uses two deployment scripts that download the image from the first argument (path).
* *four-jobs* Combination of previous examples of four jobs arranged sequentially, except two and three that are in parallel. Uses the deployment scripts of previous examples.
* *four-singularity-jobs* Same as previous example but only using singularity jobs. Uses the deployment scripts of _single_singularity_job_ example.
* *pilot-example* Dummy example to show how to model a MADF and a pilot. To work properly, deployment scripts and command properties must be modified.
